development:
  app_key:    '1012095462'
  secret_key: 'sandbox92912e2f8b83b2f2f1128177e'
  endpoint:   "http://gw.api.tbsandbox.com/router/rest"
  #oauth获取授权地址
  authorize:  "https://oauth.tbsandbox.com/authorize"
  #oauth获取令牌地址
  token: "https://oauth.tbsandbox.com/token" 
  #获取授权码回调uri
  authorize_redirect_uri: "http://127.0.0.1:3000/authorize/after_authorize"
  #获取令牌回调uri
  token_redirect_uri: "http://127.0.0.1:3000/authorize/after_token"

test:
  app_key:    '1012095462'
  secret_key: 'sandbox92912e2f8b83b2f2f1128177e'
  endpoint:   "http://gw.api.tbsandbox.com/router/rest"
  #oauth获取授权地址
  authorize:  "https://oauth.tbsandbox.com/authorize"
  #oauth获取令牌地址
  token: "https://oauth.tbsandbox.com/token" 
  #获取授权码回调uri
  authorize_redirect_uri: "http://127.0.0.1:3000/authorize/after_authorize"
  #获取令牌回调uri
  token_redirect_uri: "http://127.0.0.1:3000/authorize/after_token"

production:
  app_key:    '12095462'
  secret_key: '8ae1ea892912e2f8b83b2f2f1128177e'
  endpoint:   "http://gw.api.taobao.com/router/rest"
  #oauth获取授权地址
  authorize:  "https://oauth.taobao.com/authorize"
  #oauth获取令牌地址
  token: "https://oauth.taobao.com/token" 
  #获取授权码回调uri
  authorize_redirect_uri: "http://mazg.ssapp.co/authorize/after_authorize"
  #获取令牌回调uri
  token_redirect_uri: "http://mazg.ssapp.co/authorize/after_token"

#在服务器上测试沙箱
sandbox:
  app_key:    '1012095462'
  secret_key: 'sandbox92912e2f8b83b2f2f1128177e'
  endpoint:   "http://gw.api.tbsandbox.com/router/rest"
  #oauth获取授权地址
  authorize:  "https://oauth.tbsandbox.com/authorize"
  #oauth获取令牌地址
  token: "https://oauth.tbsandbox.com/token" 
  #获取授权码回调uri
  authorize_redirect_uri: "http://sandbox.ssapp.co/authorize/after_authorize"
  #获取令牌回调uri
  token_redirect_uri: "http://sandbox.ssapp.co/authorize/after_token"
