#coding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemsController do
  render_views
  let_valid_session
  # This should return the minimal set of attributes required to create a valid
  # Item. As you add validations to Item, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemsController. Be sure to keep this updated too.

  let!(:items_onsale_get_response) {FactoryGirl.build(:items_onsale_get_response)}
  let!(:item_get_response) {FactoryGirl.build(:item_get_response)}

  describe "GET index" do
    it "assigns all items as @items" do
      controller.should_receive(:taobao_items_list_get).and_return(items_onsale_get_response.items)
      TaobaoSDK::Session.should_receive(:invoke).with(
        method: "taobao.sellercats.list.get",
        nick:  'sandbox_cdh' 
      ).and_return(FactoryGirl.build(:sellercats_list_get_response))
      TaobaoSDK::Session.should_receive(:invoke).and_return(items_onsale_get_response)
      get :index, {}, valid_session
      assigns(:items).should eq(items_onsale_get_response.items)
    end
  end

  describe "GET show" do
    it "assigns the requested item as @item" do
      TaobaoSDK::Session.should_receive(:invoke).and_return(item_get_response)
      item = item_get_response.item
      get :show, {:id => item.num_iid}, valid_session
      assigns(:item).should eq(item)
    end
  end
  #上传生成的条码到商品图片
  #PUT items/:id/img_upload
  describe "PUT img_upload" do
    it "should success" do
      item = FactoryGirl.build(:item)
      item_img_upload_response = FactoryGirl.build(:item_img_upload_response)
      controller.should_receive(:taobao_item_get).and_return(item)
      TaobaoSDK::Session.should_receive(:invoke).and_return(item_img_upload_response)
      put :img_upload,{:id => item.num_iid},valid_session
      response.should be_success
    end
  end
  #单个商品下载到本地
  #GET items/:id/download
  describe "GET download_qr" do
    it "should success" do
      TaobaoSDK::Session.should_receive(:invoke).and_return(item_get_response)
      item = item_get_response.item
      get :download_qr, {:id => item.num_iid}, valid_session
      assigns(:item).should eq(item)
      response.should be_success
    end
  end
  #产品二纬码图片打包成zip下载到本地
  #GET items/download_zip
  describe "GET download_zip" do
    it "should success" do
      item = FactoryGirl.build(:item)
      controller.should_receive(:taobao_item_get).and_return(item)
      get :download_zip,{:format => :zip,:ids => [item.num_iid],:qr_options => {item.num_iid.to_s => {}}},valid_session
      response.should be_success
    end
  end
  #将产品图片上传到淘宝图片空间
  #POST items/picture_upload
  describe "PUT item/:id/picture_upload" do
    it "should success" do
      item = FactoryGirl.build(:item)
      controller.should_receive(:taobao_item_get).and_return(item)
      TaobaoSDK::Session.should_receive(:invoke).and_return(FactoryGirl.build(:picture_upload_response))
      put :picture_upload,{:id => item.num_iid},valid_session
      response.should be_success
    end
  end
  #GET items/:id/qr_code_img
  #获取商品图片
  describe "GET items/:id/qr_code_img" do
    it "should success" do
      item = FactoryGirl.build(:item)
      controller.should_receive(:taobao_item_get).and_return(item)
      get :qr_code_img,{id: item.num_iid},valid_session
      response.should be_success
    end
  end
end
